import './globals.css'
import { Inter } from 'next/font/google'
import SideNav from "@/app/components/SideNav";
import Header from "@/app/components/Header";
import {AppProvider} from "@/app/context";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <AppProvider>
      <Header/>
      <div className={"layout_container"}>
          <SideNav/>
          {children}
      </div>
      </AppProvider>
      </body>
      </html>
  );
}
